apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-crud-api
  namespace: simple-crud-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-crud-api
  template:
    metadata:
      labels:
        app: simple-crud-api
    spec:
      containers:
      - name: simple-crud-api
        image: guidosdocker/simple-crud-api
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: simple-crud-api
  namespace: simple-crud-api
spec:
  type: LoadBalancer
  selector:
    app: simple-crud-api
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000